table Cliente
	lineageTag: fd5abda1-5391-48b5-acad-e1ed42b5f190

	measure PromedioUnidadesPorMovimiento = ```
			
			AVERAGE(MovimientoInventario[cantidad])
			
			
			```
		lineageTag: fa18e7ed-97d1-4f5f-b791-bd765a8c7790

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeEntradas = ```
			
			DIVIDE(
			    CALCULATE(COUNTROWS(MovimientoInventario), MovimientoInventario[tipo_movimiento] = "Entrada"),
			    COUNTROWS(MovimientoInventario)
			)
			
			```
		lineageTag: 56dfe687-2425-4919-9774-3dd19c4667db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeSalidas = ```
			
			DIVIDE(
			    CALCULATE(COUNTROWS(MovimientoInventario), MovimientoInventario[tipo_movimiento] = "Salida"),
			    COUNTROWS(MovimientoInventario)
			)
			
			```
		lineageTag: 99a19886-bcfe-4071-bc8e-9c345d34be48

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ProductoYCantidadMasMovidoMes = ```
			
			VAR MesActual = MONTH(TODAY())
			VAR AnioActual = YEAR(TODAY())
			VAR TablaResumen =
			    SUMMARIZE(
			        MovimientoInventario,
			        MovimientoInventario[producto],
			        "CantidadMovida",
			            CALCULATE(
			                SUM(MovimientoInventario[cantidad]),
			                FILTER(
			                    MovimientoInventario,
			                    MONTH(MovimientoInventario[fecha]) = MesActual &&
			                    YEAR(MovimientoInventario[fecha]) = AnioActual
			                )
			            )
			    )
			VAR CantidadMaxima = MAXX(TablaResumen, [CantidadMovida])
			VAR Producto =
			    MAXX(
			        FILTER(TablaResumen, [CantidadMovida] = CantidadMaxima),
			        [producto]
			    )
			RETURN
			    "Producto: " & Producto & " (" & CantidadMaxima & " movimientos)"
			
			```
		lineageTag: 1d45e748-7305-489c-babc-cf6ac18d2755

	measure CostoTotalInventarioActual = ```
			
			SUMX(
			    Producto,
			    Producto[stock_actual] * Producto[costo_unitario]
			)
			
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 4cf367dc-f10e-4094-ba37-f6ec97038498

	measure ConsumoPorUbicacion = ```
			
			CALCULATE(
			    SUM(MovimientoInventario[cantidad]),
			    MovimientoInventario[tipo_movimiento] = "Salida"
			)
			
			```
		formatString: 0
		lineageTag: 1a0e5feb-4096-4fe6-8d29-444c29410b1f

	column id_cliente
		dataType: int64
		formatString: 0
		lineageTag: 935b95c5-7948-43a4-98b8-b766e8eaacf6
		summarizeBy: none
		sourceColumn: id_cliente

		annotation SummarizationSetBy = Automatic

	column nombre
		dataType: string
		lineageTag: d3381cdd-b3bb-495c-9bf4-247e16bee35b
		summarizeBy: none
		sourceColumn: nombre

		annotation SummarizationSetBy = Automatic

	column apellido
		dataType: string
		lineageTag: 4c145af5-d6f0-48a5-8180-80d08766c662
		summarizeBy: none
		sourceColumn: apellido

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 7ad188c3-7a35-4c3d-93be-1f35f9416462
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column fecha_nacimiento
		dataType: dateTime
		formatString: Long Date
		lineageTag: 25ffeb4e-2d9e-40d5-aa95-dd8ea3b23fe1
		summarizeBy: none
		sourceColumn: fecha_nacimiento

		variation Variación
			isDefault
			relationship: 9eb9668c-7f8f-4d54-bcc9-589df6d5eb54
			defaultHierarchy: LocalDateTable_f17f7547-1f81-4124-acb4-73c294c262e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column genero
		dataType: string
		lineageTag: d2ea0027-df08-46e5-b308-3945937a024c
		summarizeBy: none
		sourceColumn: genero

		annotation SummarizationSetBy = Automatic

	column nacionalidad
		dataType: string
		lineageTag: ce3aca88-32ab-4b7b-a8a3-79f79c723aca
		summarizeBy: none
		sourceColumn: nacionalidad

		annotation SummarizationSetBy = Automatic

	partition Cliente = m
		mode: import
		source =
				let
				    Origen = Sql.Database("172.25.224.1", "HotelDW"),
				    dbo_Cliente = Origen{[Schema="dbo",Item="Cliente"]}[Data]
				in
				    dbo_Cliente

