table Medidas
	lineageTag: 7664ced5-bf52-49ea-b323-c6350067ec58

	measure TotalReservasActivas = ```
			
			CALCULATE(
			    COUNT(Reserva[id_reserva]),
			    YEAR(Reserva[fecha_reserva]) = YEAR(TODAY()),
			    Reserva[estado_reserva] = "Check-in"
			)
			
			```
		formatString: 0
		lineageTag: 03810152-7f5f-4d06-ad7e-74d02219794d

	measure PromedioNochesPorReserva = ```
			
			AVERAGEX(
			    FILTER(
			        Reserva,
			        Reserva[estado_reserva] = "Check-in"
			    ),
			    DATEDIFF(Reserva[check_in], Reserva[check_out], DAY)
			)
			
			```
		lineageTag: 356bcb6d-9baa-4a84-93f8-a00ec1ae9472

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalReservasPorFuente = ```
			
			CALCULATE(
			    COUNT(Reserva[id_reserva]),
			    YEAR(Reserva[fecha_reserva]) = YEAR(TODAY())
			)
			
			```
		formatString: 0
		lineageTag: 033a597d-8686-4959-a9b9-57211c2bb428

	measure PromedioVisitasPorCliente = ```
			
			AVERAGEX(
			    VALUES(Visita[id_cliente]),
			    CALCULATE(COUNT(Visita[id_visita]))
			)
			
			```
		lineageTag: 7a2c23dd-21d7-43c5-998b-fa59cd7d43cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeSatisfaccionPromedio = ```
			
			AVERAGE(Encuesta[puntaje])
			
			```
		lineageTag: 7910ea7c-e19a-41e1-a6ae-62b525493b38

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ClientesNuevosEsteAño = ```
			
			CALCULATE(
			    DISTINCTCOUNT(Reserva[id_cliente]),
			    FILTER(
			        Reserva,
			        CALCULATE(
			            COUNTROWS(Reserva),
			            ALLEXCEPT(Reserva, Reserva[id_cliente])
			        ) = 1
			    ),
			    YEAR(Calendario[Date]) = YEAR(TODAY())
			)
			
			
			
			
			```
		formatString: 0
		lineageTag: 10dad83d-cca7-4170-a9d1-1ab691d03ce4

	measure ClientesRecurrentes = ```
			
			CALCULATE(
			    DISTINCTCOUNT(Reserva[id_cliente]),
			    FILTER(
			        Reserva,
			        CALCULATE(COUNTROWS(Reserva), ALLEXCEPT(Reserva, Reserva[id_cliente])) > 1
			    )
			)
			
			```
		formatString: 0
		lineageTag: 8890796c-87cc-40db-a5d3-922a8ec97f22

	measure PorcentajeClientesNuevos = ```
			
			DIVIDE(
			    [ClientesNuevosEsteAño],
			    DISTINCTCOUNT(Reserva[id_cliente]),
			    0
			) * 100
			
			```
		lineageTag: f6296806-2980-4c25-933c-3cd3e47e908e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PorcentajeClientesRecurrentes = ```
			
			DIVIDE(
			    [ClientesRecurrentes],
			    DISTINCTCOUNT(Reserva[id_cliente]),
			    0
			) * 100
			
			```
		lineageTag: 550fa987-bf01-4883-8190-8e9a609dd7f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalReservasPorMes = ```
			
			CALCULATE(
			    COUNTROWS(Reserva),
			    FILTER(
			        Reserva,
			        YEAR(Reserva[fecha_reserva]) = YEAR(TODAY()) &&
			        MONTH(Reserva[fecha_reserva]) = SELECTEDVALUE(Calendario[Mes])
			    )
			)
			
			```
		formatString: 0
		lineageTag: a64df7cc-6d4c-433d-a2d6-3c275f8500b7

	measure TotalReservasAñoActual = ```
			
			CALCULATE (
			    COUNT ( Reserva[id_reserva] ),
			    YEAR ( Reserva[fecha_reserva] ) = YEAR ( TODAY() )
			)
			
			```
		formatString: 0
		lineageTag: b7a46c50-2d95-4b68-82f8-248127fc5a54

	measure ReservasEsteAño = ```
			
			CALCULATE (
			    COUNT ( Reserva[id_reserva] ),
			    YEAR ( Reserva[fecha_reserva] ) = YEAR ( TODAY() )
			)
			
			
			```
		formatString: 0
		lineageTag: 3df37795-70cd-4a52-a800-17226cbb84be

	measure CanceladasEsteAño = ```
			
			CALCULATE (
			    COUNT ( Reserva[id_reserva] ),
			    Reserva[estado_reserva] = "Cancelada",
			    YEAR ( Reserva[fecha_reserva] ) = YEAR ( TODAY() )
			)
			
			```
		formatString: 0
		lineageTag: 5d521085-7887-4a66-bf6f-da21690de2a9

	measure TasaCancelaciones% = ```
			
			DIVIDE ( [CanceladasEsteAño], [ReservasEsteAño], 0 ) * 100
			
			```
		lineageTag: 039fbb5c-0f59-4747-aec2-cd4bc5b03da6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DuracionMediaPorFuente = ```
			
			AVERAGEX (
			    Reserva,
			    DATEDIFF ( Reserva[check_in], Reserva[check_out], DAY )
			)
			
			```
		lineageTag: 63796019-7aa6-46de-93a0-e0cc0c497603

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DuracionMediaPorFuenteAñoActual = ```
			
			CALCULATE (
			    [DuracionMediaPorFuente],
			    YEAR ( Reserva[fecha_reserva] ) = YEAR ( TODAY() )
			)
			
			```
		lineageTag: 58ebc3f0-42fa-48f7-9f84-cd568604b377

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ReservasAño =
			
			CALCULATE (
			    COUNT ( Reserva[id_reserva] ),
			    YEAR ( Reserva[fecha_reserva] ) = YEAR ( TODAY() )
			)
		formatString: 0
		lineageTag: ec8a7ad1-540e-41cc-99d3-7f827b3d2da1

	measure PagosAño = ```
			
			CALCULATE (
			    DISTINCTCOUNT ( 'pago'[id_reserva] ),
			    FILTER (
			        'Pago',
			        YEAR ( 'Pago'[fecha_pago] ) = YEAR ( TODAY() )
			    )
			)
			
			```
		formatString: 0
		lineageTag: e66b4d6e-ea5c-488f-9923-5eb834828bf0

	measure CheckInAño =
			
			CALCULATE (
			    COUNT ( Reserva[id_reserva] ),
			    Reserva[estado_reserva] = "Check-in",
			    YEAR ( Reserva[fecha_reserva] ) = YEAR ( TODAY() )
			)
		formatString: 0
		lineageTag: 18a0e335-b773-4979-bb1e-905c9582c38a

	measure PromedioSatisfaccionPorFuente = ```
			
			ROUND (
			    AVERAGEX (
			        Encuesta,            
			        Encuesta[puntaje]   
			    ),
			    2                       
			)
			```
		lineageTag: c6046ffa-09e2-4df6-bfdc-5b546cfded64

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		lineageTag: f03342c1-355e-4d20-bf50-ee5e93dfc6b4
		summarizeBy: none
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition Medidas = calculated
		mode: import
		source = {""}

	annotation PBI_Id = 7ca9ca9fda5b434795defd024a2dce72

